services:
    database:
      image: 'mysql:latest'
      container_name: ldap_database
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: db_ldap
      ports:
        - '3306'
    phpmyadmin:
      depends_on:
        - database
      image: phpmyadmin
      container_name: ldap_phpmyadmin
      restart: always
      ports:
        - '8282:80'
      environment:
        PMA_HOST: database